### ISSUE TITLE
'(BuildContext, dynamic, int) => dynamic' is not a subtype of type '(BuildContext, dynamic, int) => Widget'.

### ISSUE THREAD

**Issue by Carrein** [AbdulRahmanAlHamali/flutter_pagewise#25]
Returning `post.test()` in `itemBuilder()` yields the following error. I cannot seem to get pass it other than constructing the widget in the same class as the pagewise Widget instead of the the Post widget.

*post.dart*
```
import 'package:flutter/material.dart';
import 'package:shannon/comment_page.dart';

class Post {
  final String id;
  final String content;
  final double latitude;
  final double longitude;
  final int time;
  final String username;

  Post({this.id, this.content, this.latitude, this.longitude, this.time, this.username});

  factory Post.fromJson(Map<String, dynamic> json) {
    print(json['content']);
    return Post(
      id: json ['id'],
      content: json['content'],
      latitude: json['latitude'],
      longitude: json['longitude'],
      time: json['time'],
      username: json['username'],
    );
  }

  Widget test(){
    return ListTile(title: Text("A"));
  }
}
```
```
Performing hot restart...
Restarted application in 2,556ms.
I/flutter ( 5696): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 5696): The following assertion was thrown building FeedPage(dirty, state: _FeedPage#5841c):
I/flutter ( 5696): type '(BuildContext, dynamic, int) => dynamic' is not a subtype of type '(BuildContext, dynamic,
I/flutter ( 5696): int) => Widget'
I/flutter ( 5696):
I/flutter ( 5696): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 5696): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 5696): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 5696):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter ( 5696):
I/flutter ( 5696): When the exception was thrown, this was the stack:
I/flutter ( 5696): #0      new PagewiseListView (package:flutter_pagewise/flutter_pagewise.dart:505:26)
I/flutter ( 5696): #1      _FeedPage.build (package:shannon/feed_page.dart:75:13)
I/flutter ( 5696): #2      StatefulElement.build (package:flutter/src/widgets/framework.dart:3809:27)
I/flutter ( 5696): #3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3721:15)
I/flutter ( 5696): #4      Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 5696): #5      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter ( 5696): #6      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
I/flutter ( 5696): #7      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter ( 5696): #8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 5696): #9      Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 5696): #10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 5696): #11     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 5696): #12     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2286:33)
I/flutter ( 5696): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:676:20)
I/flutter ( 5696): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:219:5)
I/flutter ( 5696): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter ( 5696): #16     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter ( 5696): #17     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:751:7)
I/flutter ( 5696): #19     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
I/flutter ( 5696): #20     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
I/flutter ( 5696): #21     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
I/flutter ( 5696): (elided one frame from package dart:async)
I/flutter ( 5696): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by AbdulRahmanAlHamali** [comment]
Hello @Carrein, Thank you for reporting the issue. Could you please post how you are using the Pagewise widget, so that I can see the whole picture?

**Comment by Carrein** [comment]
Thanks @AbdulRahmanAlHamali. 

```
  final pageLoadController = PagewiseLoadController(
      pageSize: 10,
      pageFuture: (index) {
        return fetchFeed(index);
      });

 static Future<List<Post>> fetchFeed(index) async {
    print(index);
    postList = [];

  //populate postList..

    }).catchError((e) {
      print(e.toString());
    });
    return postList;
  }

 body: PagewiseListView(
        pageLoadController: pageLoadController,
        padding: EdgeInsets.all(10.0),
        itemBuilder: (context, entry, index) {
          return entry.test(); //cannot call method from entry (Post) - but accessing fields such as content via entry.content is and wrapping in a Text Widget is okay.
        },
```

**Comment by Carrein** [comment]
Okay I "fixed" this by assigning `entry` to a Post instance first:

```
 body: PagewiseListView(
        pageLoadController: pageLoadController,
        padding: EdgeInsets.all(10.0),
        itemBuilder: (context, entry, index) {
          //return entry.test(); cannot call method from entry (Post) - but accessing fields such as content via entry.content is and wrapping in a Text Widget is okay.
          Post post = entry;
          return post.test() //this is okay.
        },
```

**Comment by AbdulRahmanAlHamali** [comment]
Hello,
Does it work to say:
```
(context, Post entry, index) {
  return post.test();
}
```

I don't think that is a problem with Pagewise itself.

**Comment by Carrein** [comment]
> Hello,
> Does it work to say:
> 
> ```
> (context, Post entry, index) {
>   return post.test();
> }
> ```
> I don't think that is a problem with Pagewise itself.

Doesn't seem to work i.e. same error:

```
PagewiseListView(
                    pageLoadController: pageLoadController,
                    padding: EdgeInsets.all(10.0),
                    itemBuilder: (context, Comment entry, index) {
                      // commentTile = entry;
                      return entry.tile();
                    })
```

**Comment by AbdulRahmanAlHamali** [comment]
@sjmcdowall I think we had a similar typing error in Typeahead, do you remember how we solved the problem eventually?

**Comment by AbdulRahmanAlHamali** [comment]
Alright, I will look at that this week and will push a fix

**Comment by sjmcdowall** [comment]
We can grab the code that fixed it in TypeAheadField - it’s just a matter of adding <T> in a few more spots 

You can see the diffs in GutHub for the fix and do the same 

I would but my internet is basically zilch til tomorrow
