### ISSUE TITLE
Can't provide controller. Assertion failed.

### ISSUE THREAD

**Issue by lifenautjoe** [AbdulRahmanAlHamali/flutter_pagewise#31]
When trying to provide a controller as following

````dart
    return RefreshIndicator(
        key: _refreshIndicatorKey,
        onRefresh: _onRefresh,
        child: PagewiseListView(
          controller: _pagewiseLoadController,
          itemBuilder: (context, entry, index) {
            var post = entry;

            return OBPost(
              post,
              onPostDeleted: _onPostDeleted,
              key: Key(
                post.id.toString(),
              ),
            );
          },
        ));
````

An exception is thrown

````
Performing hot restart...
Syncing files to device Android SDK built for x86...
Restarted application in 2,099ms.
I/flutter (14795): Initialising universal links
I/flutter (14795): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (14795): The following assertion was thrown building OBTimelinePosts(dirty, state:
I/flutter (14795): OBTimelinePostsState#3b437):
I/flutter (14795): 'package:flutter_pagewise/flutter_pagewise.dart': Failed assertion: line 166 pos 16: '(controller ==
I/flutter (14795): null && pageSize != null && pageFuture != null) ||
I/flutter (14795):             (controller != null && pageSize == null && pageFuture == null)': is not true.
I/flutter (14795): 
I/flutter (14795): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (14795): more information in this error message to help you determine and fix the underlying cause.
I/flutter (14795): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (14795):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (14795): 
I/flutter (14795): When the exception was thrown, this was the stack:
I/flutter (14795): #2      new Pagewise (package:flutter_pagewise/flutter_pagewise.dart:166:16)
I/flutter (14795): #3      new PagewiseListView (package:flutter_pagewise/flutter_pagewise.dart:497:9)
````

The PagewiseListView has no pageSize nor pageFuture, while the controller does.

**Comment by lifenautjoe** [comment]
Uh, the argument expected is `pageLoadController` not `controller` as everywhere else in the flutter ecosystem. 🤦‍♂️

**Comment by AbdulRahmanAlHamali** [comment]
I agree that it is a bit confusing, but my problem is that I also have a `ScrollController`, which allows you to control the scrolling. This is the one that I called `controller`, to confirm with the `controller` property of `ListView` and `GridView`. Do you have another approach in mind?
