### ISSUE TITLE
Exception thrown on scrolling

### ISSUE THREAD

**Issue by lifenautjoe** [AbdulRahmanAlHamali/flutter_pagewise#33]
Scrolling down and then up causes the following exception to be thrown 

````
I/al.openbook.de(17067): Waiting for a blocking GC ProfileSaver
I/al.openbook.de(17067): WaitForGcToComplete blocked ProfileSaver on ProfileSaver for 18.457ms
I/flutter (17067): Loading with index1
I/flutter (17067): Loading with index2
I/flutter (17067): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (17067): The following assertion was thrown during performLayout():
I/flutter (17067): A RenderViewport exceeded its maximum number of layout cycles.
I/flutter (17067): RenderViewport render objects, during layout, can retry if either their slivers or their
I/flutter (17067): ViewportOffset decide that the offset should be corrected to take into account information collected
I/flutter (17067): during that layout.
I/flutter (17067): In the case of this RenderViewport object, however, this happened 10 times and still there was no
I/flutter (17067): consensus on the scroll offset. This usually indicates a bug. Specifically, it means that one of the
I/flutter (17067): following three problems is being experienced by the RenderViewport object:
I/flutter (17067):  * One of the RenderSliver children or the ViewportOffset have a bug such that they always think
I/flutter (17067):    that they need to correct the offset regardless.
I/flutter (17067):  * Some combination of the RenderSliver children and the ViewportOffset have a bad interaction such
I/flutter (17067):    that one applies a correction then another applies a reverse correction, leading to an infinite
I/flutter (17067):    loop of corrections.
I/flutter (17067):  * There is a pathological case that would eventually resolve, but it is so complicated that it
I/flutter (17067):    cannot be resolved in any reasonable number of layout passes.
I/flutter (17067): 
I/flutter (17067): When the exception was thrown, this was the stack:
I/flutter (17067): #0      RenderViewport.performLayout.<anonymous closure> (package:flutter/src/rendering/viewport.dart:1249:9)
I/flutter (17067): #1      RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1269:6)
I/flutter (17067): #2      RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1509:7)
I/flutter (17067): #3      PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:768:18)
I/flutter (17067): #4      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:281:19)
I/flutter (17067): #5      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:677:13)
I/flutter (17067): #6      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:219:5)
I/flutter (17067): #7      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (17067): #8      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter (17067): #9      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter (17067): #10     _invoke (dart:ui/hooks.dart:154:13)
I/flutter (17067): #11     _drawFrame (dart:ui/hooks.dart:143:3)
I/flutter (17067): 
I/flutter (17067): The following RenderObject was being processed when the exception was fired:
I/flutter (17067):   RenderViewport#58d0d NEEDS-LAYOUT NEEDS-PAINT
I/flutter (17067):   creator: Viewport ← _ScrollableScope ← IgnorePointer-[GlobalKey#99acc] ← Semantics ← Listener ←
I/flutter (17067):   _GestureSemantics ← RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#f5978] ←
I/flutter (17067):   _ScrollSemantics-[GlobalKey#df4c1] ← RepaintBoundary ← CustomPaint ← RepaintBoundary ←
I/flutter (17067):   NotificationListener<ScrollNotification> ← ⋯
I/flutter (17067):   parentData: <none> (can use size)
I/flutter (17067):   constraints: BoxConstraints(0.0<=w<=411.4, 0.0<=h<=565.4)
I/flutter (17067):   layer: OffsetLayer#82aa5
I/flutter (17067):   size: Size(411.4, 565.4)
I/flutter (17067):   axisDirection: down
I/flutter (17067):   crossAxisDirection: right
I/flutter (17067):   offset: ScrollPositionWithSingleContext#108c9(offset: 604.7, range: 0.0..5459.8, viewport: 565.4,
I/flutter (17067):   ScrollableState, AlwaysScrollableScrollPhysics -> ClampingScrollPhysics,
I/flutter (17067):   BallisticScrollActivity#e8181(AnimationController#fa432(▶ 604.710; for BallisticScrollActivity)),
I/flutter (17067):   ScrollDirection.forward)
I/flutter (17067):   anchor: 0.0
I/flutter (17067): This RenderObject had the following descendants (showing up to depth 5):
I/flutter (17067):   RenderSliverPadding#6aed6 relayoutBoundary=up1 NEEDS-PAINT
I/flutter (17067):     RenderSliverList#244b5 relayoutBoundary=up2 NEEDS-PAINT
I/flutter (17067):       RenderIndexedSemantics#ef6a9 relayoutBoundary=up3 NEEDS-PAINT
I/flutter (17067):         RenderRepaintBoundary#454ba relayoutBoundary=up4 NEEDS-PAINT
I/flutter (17067):           RenderFlex#9d270 relayoutBoundary=up5 NEEDS-PAINT
I/flutter (17067):       RenderIndexedSemantics#75d75 relayoutBoundary=up3
I/flutter (17067):         RenderRepaintBoundary#ee7fa relayoutBoundary=up4
I/flutter (17067):           RenderFlex#dd278 relayoutBoundary=up5
I/flutter (17067):       RenderIndexedSemantics#da148 relayoutBoundary=up3
I/flutter (17067):         RenderRepaintBoundary#cd0f4 relayoutBoundary=up4
I/flutter (17067):           RenderFlex#28339 relayoutBoundary=up5
I/flutter (17067):       RenderIndexedSemantics#8d22e relayoutBoundary=up3
I/flutter (17067):         RenderRepaintBoundary#85151 relayoutBoundary=up4
I/flutter (17067):           RenderFlex#044e1 relayoutBoundary=up5
I/flutter (17067):       RenderIndexedSemantics#f6f71 NEEDS-LAYOUT
I/flutter (17067):         RenderRepaintBoundary#b6744 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (17067):           RenderFlex#ec9dc NEEDS-LAYOUT NEEDS-PAINT
I/flutter (17067):       RenderIndexedSemantics#a3b06 NEEDS-LAYOUT
I/flutter (17067):         RenderRepaintBoundary#c4ffe NEEDS-LAYOUT NEEDS-PAINT
I/flutter (17067):           RenderFlex#7e732 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (17067):       RenderIndexedSemantics#84037 NEEDS-LAYOUT
I/flutter (17067):         RenderRepaintBoundary#d9b0e NEEDS-LAYOUT NEEDS-PAINT
I/flutter (17067):           RenderFlex#f8570 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (17067):       RenderIndexedSemantics#1b234 NEEDS-LAYOUT
I/flutter (17067):         RenderRepaintBoundary#d4b6f NEEDS-LAYOUT NEEDS-PAINT
I/flutter (17067):           RenderFlex#b7edc NEEDS-LAYOUT NEEDS-PAINT
I/flutter (17067):       RenderIndexedSemantics#3edca NEEDS-LAYOUT
I/flutter (17067):         RenderRepaintBoundary#12a75 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (17067):           RenderFlex#fcaa5 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (17067): ════════════════════════════════════════════════════════════════════════════════════════════════════
````

**Comment by AbdulRahmanAlHamali** [comment]
Hello @lifenautjoe, Thank you for reporting the issue. I suspect that you have a GridView. Correct?

I have had the same problem too, and it is related to the way the loading widget is rendered when the remaining number of entries is not divisible by the ChildCount.

The problem is that I am currently extremely low on time. I will try to give the issue a shot over the weekend, but I can't guarantee. 

Would you be interested in participating, and opening a pull request? I am looking for collaborators! :)

**Comment by lifenautjoe** [comment]
Awesome work @AbdulRahmanAlHamali !
