### ISSUE TITLE
PagewiseLoadController<dynamic>

### ISSUE THREAD

**Issue by aabanaag** [AbdulRahmanAlHamali/flutter_pagewise#62]
I got this error. 

```
flutter: #125    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame 
package:flutter/…/widgets/binding.dart:701
flutter: #126    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback 
package:flutter/…/rendering/binding.dart:268
flutter: #127    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback 
package:flutter/…/scheduler/binding.dart:988
flutter: #128    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame 
package:flutter/…/scheduler/binding.dart:928
flutter: #129    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame 
package:flutter/…/scheduler/binding.dart:840
flutter: #133    _invoke (dart:ui/hooks.dart:209:10)
flutter: #134    _drawFrame (dart:ui/hooks.dart:168:3)
flutter: (elided 4 frames from package dart:async)
flutter:
flutter: The PagewiseLoadController<dynamic> sending notification was:
flutter:   Instance of 'PagewiseLoadController<dynamic>'
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
```
I have a simple implementation to which I just have
```
Widget build(BuildContext context) {
    return PagewiseListView(
      pageSize: limit,
      itemBuilder: (context, entry, _) {
        AttendeeModel attendee = entry;
        return _buildAttendee(context, attendee);
      },
      pageFuture: (index) =>
          this.attendeeBloc.getAttendees(context, (index * limit)),
      loadingBuilder: (context) => LoadingMask(),
    );
  }
```

**Comment by aabanaag** [comment]
Fixed it just needed to add `Future<List>` to my method so that it won't expect `Future<dynamic>`
