### ISSUE TITLE
Unhandled Exception: A PagewiseLoadController<Log> was used after being disposed.

### ISSUE THREAD

**Issue by sbJonas** [AbdulRahmanAlHamali/flutter_pagewise#66]
Hi,

i got an app with a tabbed navigation. When i switch tabs (where one tab contains a PagewiseSliverList) very fast i get following exception:

```[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: A PagewiseLoadController<Log> was used after being disposed.
	Once you have called dispose() on a PagewiseLoadController<Log>, it can no longer be used.
	#0      ChangeNotifier._debugAssertNotDisposed.<anonymous closure> (package:flutter/src/foundation/change_notifier.dart:105:9)
	#1      ChangeNotifier._debugAssertNotDisposed (package:flutter/src/foundation/change_notifier.dart:111:6)
	#2      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:200:12)
	#3      PagewiseLoadController.fetchNewPage (package:flutter_pagewise/flutter_pagewise.dart:497:7)
	<asynchronous suspension>
	#4      PagewiseState._itemBuilder (package:flutter_pagewise/flutter_pagewise.dart:270:35)
	#5      SliverChildBuilderDelegate.build (package:flutter/src/widgets/sliver.dart:398:15)
	#6      SliverMultiBoxAdaptorElement._build.<anonymous closure> (package:flutter/src/widgets/sliver.dart:1006:67)
	#7      _HashMap.putIfAbsent (dart:collection-patch/collection_patch.dart:137:29)
	#8      SliverMultiBoxAdaptorElement._build (package:flutter/src/widgets/sliver.dart:1006:26)
	#9      SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:1019:55)
	#10     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2258:19)
	#11     SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:1012:11)
	#12     RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:275:23)
	#13     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1740:58)
	#14     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:797:15)
	#15     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1740:13)
	#16     RenderSliverMultiBoxAdaptor._createOrObtainChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:264:5)
	#17     RenderSliverMultiBoxAdaptor.addInitialChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:348:5)
	#18     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:78:12)
	#19     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
	#20     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:182:11)
	#21     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
	#22     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:407:13)
	#23     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1322:12)
	#24     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1240:20)
	#25     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
	#26     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
	#27     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
	#28     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
	#29     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
	#30     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
	#31     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
	#32     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
	#33     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
	#34     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
	#35     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
	#36     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
	#37     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
	#38     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:510:15)
	#39     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
	#40     RenderSliverFillRemaining.performLayout (package:flutter/src/rendering/sliver_fill.dart:122:13)
	#41     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
	#42     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:407:13)
	#43     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1322:12)
	#44     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1240:20)
	#45     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1519:7)
	#46     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:766:18)
	#47     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:347:19)
	#48     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:701:13)
	#49     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
	#50     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1012:15)
	#51     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:952:9)
	#52     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:864:5)
	#53     _rootRun (dart:async/zone.dart:1124:13)
	#54     _CustomZone.run (dart:async/zone.dart:1021:19)
	#55     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
	#56     _invoke (dart:ui/hooks.dart:219:10)
	#57     _drawFrame (dart:ui/hooks.dart:178:3)```

Since this only occurs if the switch is really fast it is not that big issue.
I tried checking if the PagewiseLoadController is null before using it (and set it to null after disposing), but it did not help. So i guess solely setting up the Controller in initState() and immediately dispose it after that (via a fast tab switch) is causing this exception. (I am really new to flutter, so this may be completely wrong :) )

**Comment by luckv** [comment]
I have the same exception. But It happens only when I pop a new route on top of the current page
